LUNA FUCK U SCAMMER CRACKED BY CRAZYX


local genv = getgenv()
local fenv = getfenv()
genv["25ms was here :)"] = function()

end
loadstring("return pcall(function()return 1/\"abc\"end)")
loadstring("\nreturn pcall(function()return 1/\"abc\"end)")
fenv.loadui = function(_5, _5_2, _5_3, _5_4, ...)
    local _ = fenv.LPH_OBFUSCATED
    fenv.LPH_NO_UPVALUES = function(...)
        local _ = fenv.fl15GIwCrNTI
        return ...
    end
    fenv.LPH_NO_VIRTUALIZE = function(...)
        local _ = fenv.SgreC5xsjtoq8Z
        return ...
    end
    local _callhookfunction11 = hookfunction(type, function(_12, ...)
        local _ = fenv.Old
        error(nil, "line 3: attempt to call a nil value")
    end)
    fenv.Old = _callhookfunction11
    identifyexecutor()
    game:GetService("ReplicatedStorage"):WaitForChild("network"):WaitForChild("Shared")
    game:GetService("Lighting")
    local _Profiles30 = game:GetService("ReplicatedStorage").network.Profiles
    local _call32 = _Profiles30:FindFirstChild(game:GetService("Players").LocalPlayer.UserId)
    local _ = _call32.level
    local _ = _call32.stats
    local _call36 = game:GetService("InsertService")
    local _40 = loadstring(game:HttpGet("https://raw.githubusercontent.com/depthso/Dear-ReGui/refs/heads/main/ReGui.lua"))()
    _40:Init({
        Prefabs = _call36:LoadLocalAsset("rbxassetid://" .. _40.PrefabsId),
    })
    _40:DefineTheme("Pink Theme", {
        TitleBarBgActive = Color3.fromRGB(3, 3, 3),
        ResizeGrab = Color3.fromRGB(50, 45, 50),
        WindowBg = Color3.fromRGB(2, 2, 2),
        TitleBarBg = Color3.fromRGB(5, 30, 35),
        Text = Color3.fromRGB(0, 180, 200),
        Border = Color3.fromRGB(4, 0, 0),
    })
    local _call64 = _40:TabsWindow({
        Theme = "Pink Theme",
        Title = "Spectra Hub | RFL/RF24",
        Size = UDim2.fromOffset(319, 219),
    })
    local _call66 = _call64:CreateTab({
        Name = "Uzanma Aç/Kapat",
    })
    local _call68 = _call64:CreateTab({
        Name = "Oyuncu",
    })
    local _call71 = _call64:CreateTab({
        Name = "Top Modları",
    })
    _call64:CreateTab({
        Name = "Takımlar",
    })
    _call66:Checkbox({
        Value = false,
        Callback = function(_75, _75_2, ...)
            local _ = fenv["1O1qwEHwmtb4b"]
        end,
        Label = "Uzanma Aç/Kapat",
    })
    _call66:SliderInt({
        Minimum = 1,
        Label = "Uzaklık (stud)",
        Value = 1,
        Callback = function(_79, _79_2, _79_3, _79_4, _79_5, ...)
            local _ = fenv.t89y63rO5rkNly
        end,
        Maximum = 20,
    })
    local _call84 = game:GetService("CollectionService")
    local _LocalPlayer87 = game:GetService("Players").LocalPlayer
    for _89, _89_2 in getgc(true) do
    end
    for _92, _92_2 in _call84:GetTagged("Ball") do
        _92_2:IsA("BasePart")
        local _callgetrawmetatable95 = getrawmetatable(_92_2)
        local _96, _96_2, _96_3 = table.clone(_callgetrawmetatable95)
        setreadonly(_callgetrawmetatable95, false)
        local __index98 = _96.__index
        newcclosure(function(_99, _99_2, _99_3, _99_4, _99_5, _99_6, _99_7, ...)
            checkcaller()
            local _ = fenv.jQpm8JX2WSO4M
            return __index98(_99, _99_2)
        end)
        _96.__index = function(...)
            local _106_vararg1, _106_vararg2 = ...
            checkcaller()
            return __index98(_106_vararg1, _106_vararg2)
        end
        setrawmetatable(_92_2, _96)
        local _ = fenv.Ub5ohpPYj5P5M
    end
    _call84:GetInstanceAddedSignal("Ball"):Connect(function(_115, _115_2, _115_3, _115_4, _115_5, _115_6, ...)
        _115:IsA("BasePart")
        local _callgetrawmetatable118 = getrawmetatable(_115)
        local _119, _119_2, _119_3 = table.clone(_callgetrawmetatable118)
        setreadonly(_callgetrawmetatable118, false)
        local __index121 = _119.__index
        newcclosure(function(_122, _122_2, _122_3, _122_4, _122_5, _122_6, _122_7, ...)
            checkcaller()
            return __index121(_122, _122_2)
        end)
        _119.__index = function(...)
            local _128_vararg1, _128_vararg2 = ...
            checkcaller()
            return __index121(_128_vararg1, _128_vararg2)
        end
        setrawmetatable(_115, _119)
    end)
    _call84:GetInstanceRemovedSignal("Ball"):Connect(function(_136, ...)
        local _137, _137_2, _137_3 = table.find({
            [1] = _92_2,
            [2] = _115,
        }, _136)
        table.remove({
            [1] = _92_2,
            [2] = _115,
        }, _137)
        local _ = fenv.K0QWzmwkqC4Y
    end)
    local _ = _LocalPlayer87.Character
    _LocalPlayer87.Character:WaitForChild("HumanoidRootPart")
    local _ = fenv.x9b7XSA88kK4a
    _LocalPlayer87.CharacterAdded:Connect(function(_148, ...)
        _148:WaitForChild("HumanoidRootPart")
    end)
    game:GetService("RunService").Heartbeat:Connect(function(_154, _154_2, ...)
        local _call156 = OverlapParams.new()
        _call156.FilterType = Enum.RaycastFilterType.Whitelist
        _call156.FilterDescendantsInstances = {
            [1] = _92_2,
            [2] = _115,
        }
        local _call163 = workspace:GetPartBoundsInBox(_call150.CFrame, Vector3.new(_79_2, _79_2, _79_2), _call156)
        local _ = # _call163
        table.sort(_call163, function(_166, _166_2, _166_3, _166_4, _166_5, _166_6, ...)
            local _ = (_166.Position - _call150.Position).Magnitude < (_166_2.Position - _call150.Position).Magnitude
            local _ = fenv.VG02ZssCt5nSQh
            return true
        end)
        local _Idx177 = _call163[1]
        local _call179 = _148:FindFirstChild("LeftFoot")
        firetouchinterest(_call179, _Idx177, 0)
        firetouchinterest(_call179, _Idx177, 1)
        local _call183 = _148:FindFirstChild("RightFoot")
        firetouchinterest(_call183, _Idx177, 0)
        firetouchinterest(_call183, _Idx177, 1)
        local _call187 = _148:FindFirstChild("UpperTorso")
        firetouchinterest(_call187, _Idx177, 0)
        firetouchinterest(_call187, _Idx177, 1)
        local _call191 = _148:FindFirstChild("Head")
        firetouchinterest(_call191, _Idx177, 0)
        firetouchinterest(_call191, _Idx177, 1)
        local _call195 = _148:FindFirstChild("LeftHand")
        firetouchinterest(_call195, _Idx177, 0)
        firetouchinterest(_call195, _Idx177, 1)
        local _call199 = _148:FindFirstChild("Collide")
        firetouchinterest(_call199, _Idx177, 0)
        firetouchinterest(_call199, _Idx177, 1)
        local _ = fenv["1ZgmB7BovbzgTa"]
        local _ = (_115.Position - _call150.Position).Magnitude < (_92_2.Position - _call150.Position).Magnitude
        local _ = fenv.m27FAUpQGtNm
        local _ = (_115.Position - _call150.Position).Magnitude
        local _ = _115:GetAttribute("networkOwner") == _LocalPlayer87.UserId
        local _ = fenv.getNetwork
        local _ = fenv.KkU4KSi4kZXaaD
    end)
    _LocalPlayer87.CharacterAdded:Connect(function(_226, ...)
        task.wait(1)
        local _ = fenv["8fo1Oj6qwazv"]
    end)
    task.spawn(function(_230, ...)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        error(nil, "internal 518: <25ms: infinitelooperror>")
    end)
    local _ = fenv.DAmIeQhTUWLZ
    _call68:Checkbox({
        Value = false,
        Callback = function(_234, _234_2, _234_3, _234_4, ...)
            local _ = fenv.Bt5VuBtBjRBkp8
        end,
        Label = "Sonsuz Dayanıklılık",
    })
    local _LocalPlayer240 = game:GetService("Players").LocalPlayer
    _LocalPlayer240.Character:WaitForChild("HumanoidRootPart")
    Vector3.new(0, - 196, 0)
    Instance.new("Attachment")
    local _call249 = workspace:FindFirstChild("PredictionVisuals")
    _call249.Name = "PredictionVisuals"
    game:GetService("RunService").RenderStepped:Connect(function(_253, _253_2, ...)
        local _ = fenv["6bnwNSYfBYkosQ"]
        local _ = fenv.TERBOm7mjijL
    end)
    _LocalPlayer240.CharacterAdded:Connect(function(_259, _259_2, _259_3, _259_4, _259_5, _259_6, ...)
        _259:WaitForChild("HumanoidRootPart")
        local _ = fenv.ndSKWgbcEBltYa
    end)
    _call71:Checkbox({
        Value = false,
        Callback = function(_265, _265_2, _265_3, ...)
            local _ = fenv.wQpwIqwgIxJD
        end,
        Label = "Top Tahmini",
    })
    local _call277 = game:GetService("Players").LocalPlayer:WaitForChild("PlayerScripts"):WaitForChild("mechanics"):WaitForChild("kick"):WaitForChild("binds")
    local _ = fenv.ELAbDHqutnTb
    for _281, _281_2 in _call277:GetChildren() do
        _281_2:IsA("ModuleScript")
        for _286, _286_2 in _281_2:GetChildren() do
            _286_2:IsA("ModuleScript")
            for _291, _291_2 in _286_2:GetChildren() do
                _291_2:IsA("ModuleScript")
                for _296, _296_2 in _291_2:GetChildren() do
                    _296_2:IsA("ModuleScript")
                    for _301, _301_2 in _296_2:GetChildren() do
                        _301_2:IsA("ModuleScript")
                        for _306, _306_2 in _301_2:GetChildren() do
                            _306_2:IsA("ModuleScript")
                            for _311, _311_2 in _306_2:GetChildren() do
                                _311_2:IsA("ModuleScript")
                                for _316, _316_2 in _311_2:GetChildren() do
                                    _316_2:IsA("ModuleScript")
                                    for _321, _321_2 in _316_2:GetChildren() do
                                        _321_2:IsA("ModuleScript")
                                        for _326, _326_2 in _321_2:GetChildren() do
                                            _326_2:IsA("ModuleScript")
                                            for _331, _331_2 in _326_2:GetChildren() do
                                                _331_2:IsA("ModuleScript")
                                                for _336, _336_2 in _331_2:GetChildren() do
                                                    _336_2:IsA("ModuleScript")
                                                    for _341, _341_2 in _336_2:GetChildren() do
                                                        _341_2:IsA("ModuleScript")
                                                        for _346, _346_2 in _341_2:GetChildren() do
                                                            _346_2:IsA("ModuleScript")
                                                            error(nil, "internal 518: <25ms: infinitelooperror>")
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end
local _ = fenv.KiA4eAWjZLcF
return function(_351, _351_2, _351_3, _351_4, _351_5, _351_6, ...)
    local _call355 = game:GetService("HttpService")
    local _call357 = _call355:JSONDecode(game:HttpGet("https://keyauth.win/api/1.2/?type=init&name=SPECTRALUNA&ownerid=BSzFLdc5kA"))
    local _ = _call357.success
    local _ = fenv.EhzLcn1yKszi
    local _call362 = game:GetService("RbxAnalyticsService")
    local _call377 = game:GetService("HttpService")
    local _ = _call377:JSONDecode(game:HttpGet("https://keyauth.win/api/1.2/?type=license&key=" .. _351 .. "&sessionid=" .. _call357.sessionid .. "&name=" .. "SPECTRALUNA" .. "&ownerid=" .. "BSzFLdc5kA" .. "&hwid=" .. _call362:GetClientId())).success
    game.StarterGui:SetCore("SendNotification", {
        Text = "Key Verified. Enjoy :D",
        Title = "Spectra Hub",
        Duration = 5,
    })
    local _ = fenv.DXXNER2A2uiFxt
    fenv.LPH_NO_UPVALUES = function(...)
        return ...
    end
    fenv.LPH_NO_VIRTUALIZE = function(...)
        return ...
    end
    local _callhookfunction387 = hookfunction(type, function(_388, ...)
        _callhookfunction11(_388)
        local _ = fenv.M5theqNnplm3Kj
        return _callhookfunction11(_388)
    end)
    fenv.Old = _callhookfunction387
    identifyexecutor()
    game:GetService("ReplicatedStorage"):WaitForChild("network"):WaitForChild("Shared")
    game:GetService("Lighting")
    local _Profiles408 = game:GetService("ReplicatedStorage").network.Profiles
    local _call410 = _Profiles408:FindFirstChild(game:GetService("Players").LocalPlayer.UserId)
    local _ = _call410.level
    local _ = _call410.stats
    local _call414 = game:GetService("InsertService")
    local _418 = loadstring(game:HttpGet("https://raw.githubusercontent.com/depthso/Dear-ReGui/refs/heads/main/ReGui.lua"))()
    _418:Init({
        Prefabs = _call414:LoadLocalAsset("rbxassetid://" .. _418.PrefabsId),
    })
    _418:DefineTheme("Pink Theme", {
        TitleBarBgActive = Color3.fromRGB(3, 3, 3),
        ResizeGrab = Color3.fromRGB(50, 45, 50),
        WindowBg = Color3.fromRGB(2, 2, 2),
        TitleBarBg = Color3.fromRGB(5, 30, 35),
        Text = Color3.fromRGB(0, 180, 200),
        Border = Color3.fromRGB(4, 0, 0),
    })
    local _call442 = _418:TabsWindow({
        Theme = "Pink Theme",
        Title = "Spectra Hub | RFL/RF24",
        Size = UDim2.fromOffset(319, 219),
    })
    local _call444 = _call442:CreateTab({
        Name = "Uzanma Aç/Kapat",
    })
    local _call446 = _call442:CreateTab({
        Name = "Oyuncu",
    })
    local _call449 = _call442:CreateTab({
        Name = "Top Modları",
    })
    _call442:CreateTab({
        Name = "Takımlar",
    })
    _call444:Checkbox({
        Value = false,
        Callback = function(_453, _453_2, ...)
        end,
        Label = "Uzanma Aç/Kapat",
    })
    _call444:SliderInt({
        Minimum = 1,
        Label = "Uzaklık (stud)",
        Value = 1,
        Callback = function(_456, _456_2, _456_3, _456_4, _456_5, ...)
        end,
        Maximum = 20,
    })
    local _call460 = game:GetService("CollectionService")
    local _LocalPlayer463 = game:GetService("Players").LocalPlayer
    for _465, _465_2 in getgc(true) do
    end
    for _468, _468_2 in _call460:GetTagged("Ball") do
        _468_2:IsA("BasePart")
        local _callgetrawmetatable471 = getrawmetatable(_468_2)
        local _472, _472_2, _472_3 = table.clone(_callgetrawmetatable471)
        setreadonly(_callgetrawmetatable471, false)
        local __index474 = _472.__index
        newcclosure(function(_475, _475_2, _475_3, _475_4, _475_5, _475_6, _475_7, ...)
            checkcaller()
            return __index474(_475, _475_2)
        end)
        _472.__index = function(...)
            local _481_vararg1, _481_vararg2 = ...
            checkcaller()
            return __index474(_481_vararg1, _481_vararg2)
        end
        setrawmetatable(_468_2, _472)
    end
    _call460:GetInstanceAddedSignal("Ball"):Connect(function(_489, _489_2, _489_3, _489_4, _489_5, _489_6, ...)
        _489:IsA("BasePart")
        local _callgetrawmetatable492 = getrawmetatable(_489)
        local _493, _493_2, _493_3 = table.clone(_callgetrawmetatable492)
        setreadonly(_callgetrawmetatable492, false)
        local __index495 = _493.__index
        newcclosure(function(_496, _496_2, _496_3, _496_4, _496_5, _496_6, _496_7, ...)
            checkcaller()
            return __index495(_496, _496_2)
        end)
        _493.__index = function(...)
            local _502_vararg1, _502_vararg2 = ...
            checkcaller()
            return __index495(_502_vararg1, _502_vararg2)
        end
        setrawmetatable(_489, _493)
    end)
    _call460:GetInstanceRemovedSignal("Ball"):Connect(function(_510, ...)
        local _511, _511_2, _511_3 = table.find({
            [1] = _468_2,
            [2] = _489,
        }, _510)
        table.remove({
            [1] = _468_2,
            [2] = _489,
        }, _511)
    end)
    local _ = _LocalPlayer463.Character
    _LocalPlayer463.Character:WaitForChild("HumanoidRootPart")
    _LocalPlayer463.CharacterAdded:Connect(function(_520, ...)
        _520:WaitForChild("HumanoidRootPart")
    end)
    game:GetService("RunService").Heartbeat:Connect(function(_526, _526_2, ...)
        local _call528 = OverlapParams.new()
        _call528.FilterType = Enum.RaycastFilterType.Whitelist
        _call528.FilterDescendantsInstances = {
            [1] = _468_2,
            [2] = _489,
        }
        local _call535 = workspace:GetPartBoundsInBox(_call522.CFrame, Vector3.new(_456_2, _456_2, _456_2), _call528)
        local _ = # _call535
        table.sort(_call535, function(_538, _538_2, _538_3, _538_4, _538_5, _538_6, ...)
            local _ = (_538.Position - _call522.Position).Magnitude < (_538_2.Position - _call522.Position).Magnitude
            return true
        end)
        local _Idx548 = _call535[1]
        local _call550 = _520:FindFirstChild("LeftFoot")
        firetouchinterest(_call550, _Idx548, 0)
        firetouchinterest(_call550, _Idx548, 1)
        local _call554 = _520:FindFirstChild("RightFoot")
        firetouchinterest(_call554, _Idx548, 0)
        firetouchinterest(_call554, _Idx548, 1)
        local _call558 = _520:FindFirstChild("UpperTorso")
        firetouchinterest(_call558, _Idx548, 0)
        firetouchinterest(_call558, _Idx548, 1)
        local _call562 = _520:FindFirstChild("Head")
        firetouchinterest(_call562, _Idx548, 0)
        firetouchinterest(_call562, _Idx548, 1)
        local _call566 = _520:FindFirstChild("LeftHand")
        firetouchinterest(_call566, _Idx548, 0)
        firetouchinterest(_call566, _Idx548, 1)
        local _call570 = _520:FindFirstChild("Collide")
        firetouchinterest(_call570, _Idx548, 0)
        firetouchinterest(_call570, _Idx548, 1)
        local _ = (_489.Position - _call522.Position).Magnitude < (_468_2.Position - _call522.Position).Magnitude
        local _ = (_489.Position - _call522.Position).Magnitude
        local _ = _489:GetAttribute("networkOwner") == _LocalPlayer463.UserId
    end)
    _LocalPlayer463.CharacterAdded:Connect(function(_593, ...)
        task.wait(1)
    end)
    task.spawn(function(_596, ...)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        task.wait(0.5)
        error(nil, "internal 518: <25ms: infinitelooperror>")
    end)
    _call446:Checkbox({
        Value = false,
        Callback = function(_599, _599_2, _599_3, _599_4, ...)
        end,
        Label = "Sonsuz Dayanıklılık",
    })
    local _LocalPlayer604 = game:GetService("Players").LocalPlayer
    _LocalPlayer604.Character:WaitForChild("HumanoidRootPart")
    Vector3.new(0, - 196, 0)
    Instance.new("Attachment")
    local _call613 = workspace:FindFirstChild("PredictionVisuals")
    _call613.Name = "PredictionVisuals"
    game:GetService("RunService").RenderStepped:Connect(function(_617, _617_2, ...)
    end)
    _LocalPlayer604.CharacterAdded:Connect(function(_621, _621_2, _621_3, _621_4, _621_5, _621_6, ...)
        _621:WaitForChild("HumanoidRootPart")
    end)
    _call449:Checkbox({
        Value = false,
        Callback = function(_626, _626_2, _626_3, ...)
        end,
        Label = "Top Tahmini",
    })
    for _640, _640_2 in game:GetService("Players").LocalPlayer:WaitForChild("PlayerScripts"):WaitForChild("mechanics"):WaitForChild("kick"):WaitForChild("binds"):GetChildren() do
        _640_2:IsA("ModuleScript")
        for _645, _645_2 in _640_2:GetChildren() do
            _645_2:IsA("ModuleScript")
            for _650, _650_2 in _645_2:GetChildren() do
                _650_2:IsA("ModuleScript")
                for _655, _655_2 in _650_2:GetChildren() do
                    _655_2:IsA("ModuleScript")
                    for _660, _660_2 in _655_2:GetChildren() do
                        _660_2:IsA("ModuleScript")
                        for _665, _665_2 in _660_2:GetChildren() do
                            _665_2:IsA("ModuleScript")
                            for _670, _670_2 in _665_2:GetChildren() do
                                _670_2:IsA("ModuleScript")
                                for _675, _675_2 in _670_2:GetChildren() do
                                    _675_2:IsA("ModuleScript")
                                    for _680, _680_2 in _675_2:GetChildren() do
                                        _680_2:IsA("ModuleScript")
                                        for _685, _685_2 in _680_2:GetChildren() do
                                            _685_2:IsA("ModuleScript")
                                            for _690, _690_2 in _685_2:GetChildren() do
                                                _690_2:IsA("ModuleScript")
                                                for _695, _695_2 in _690_2:GetChildren() do
                                                    _695_2:IsA("ModuleScript")
                                                    for _700, _700_2 in _695_2:GetChildren() do
                                                        _700_2:IsA("ModuleScript")
                                                        for _705, _705_2 in _700_2:GetChildren() do
                                                            _705_2:IsA("ModuleScript")
                                                            error(nil, "internal 518: <25ms: infinitelooperror>")
                                                        end
                                                    end
                                                end
                                            end
                                        end
                                    end
                                end
                            end
                        end
                    end
                end
            end
        end
    end
end
